#!/bin/bash
# Local development runner for Healing Space UK.
#
# - Creates a Python venv and installs requirements (first run only).
# - Generates a local .env with safe DEV secrets if one does not exist
#   (strong SECRET_KEY, a valid Fernet ENCRYPTION_KEY, salts, placeholder Groq key).
# - Starts the Flask app in DEBUG on http://localhost:5000.
#
# Prerequisites: a running PostgreSQL and a database the .env points at (see
# docs/operations/LOCAL_DEVELOPMENT.md). This script does NOT create the database.
#
# Usage:  ./scripts/dev_run.sh
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

VENV_DIR="venv"
ENV_FILE=".env"

if [ ! -d "$VENV_DIR" ]; then
  echo "📦 Creating virtualenv ($VENV_DIR)..."
  python3 -m venv "$VENV_DIR"
fi
# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"

echo "📥 Installing requirements..."
pip install --quiet --upgrade pip
pip install --quiet -r requirements.txt

if [ ! -f "$ENV_FILE" ]; then
  echo "🔐 No .env found — generating one with DEV secrets (git-ignored)..."
  SECRET_KEY="$(python -c 'import secrets; print(secrets.token_hex(32))')"
  ENCRYPTION_KEY="$(python -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())')"
  PIN_SALT="$(python -c 'import secrets; print(secrets.token_hex(16))')"
  ANON_SALT="$(python -c 'import secrets; print(secrets.token_hex(16))')"
  cat > "$ENV_FILE" <<EOF
# LOCAL DEV ONLY — generated by scripts/dev_run.sh. Do NOT commit or reuse in production.
DEBUG=1
# Point this at your local Postgres database (create it first — see LOCAL_DEVELOPMENT.md):
DATABASE_URL=postgresql://healing_space:healing_space_dev_pass@localhost:5432/healing_space
SECRET_KEY=$SECRET_KEY
ENCRYPTION_KEY=$ENCRYPTION_KEY
PIN_SALT=$PIN_SALT
ANONYMIZATION_SALT=$ANON_SALT
# Replace with a real Groq key to use AI chat (app still starts without it in DEBUG):
GROQ_API_KEY=gsk_replace_me
EOF
  echo "   wrote $ENV_FILE (edit DATABASE_URL / GROQ_API_KEY as needed)."
fi

echo "🌐 Starting Healing Space on http://localhost:5000 (Ctrl+C to stop)..."
exec python api.py
